# Generated by Django 4.2.26 on 2025-12-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamiento',
            options={'ordering': ['-created_at'], 'verbose_name': 'Agendamiento', 'verbose_name_plural': 'Agendamientos'},
        ),
        migrations.AlterModelOptions(
            name='incidencia',
            options={'ordering': ['-created_at'], 'verbose_name': 'Incidencia', 'verbose_name_plural': 'Incidencias'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AlterField(
            model_name='agendamiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('efectuado', 'Efectuado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=12),
        ),
        migrations.AlterField(
            model_name='agendamiento',
            name='fecha_retiro',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='codigo',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('resuelta', 'Resuelta'), ('rechazada', 'Rechazada')], db_index=True, default='pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='tipo',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='rut',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
        migrations.AddIndex(
            model_name='agendamiento',
            index=models.Index(fields=['trabajador', 'estado'], name='agend_trab_est_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamiento',
            index=models.Index(fields=['fecha_retiro', 'estado'], name='agend_fecha_est_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamiento',
            index=models.Index(fields=['ciclo', 'estado'], name='agend_ciclo_est_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['estado', 'created_at'], name='incid_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['tipo', 'estado'], name='incid_tipo_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['uuid'], name='ticket_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado', 'created_at'], name='ticket_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['trabajador', 'ciclo'], name='ticket_trabajador_ciclo_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ttl_expira_at'], name='ticket_ttl_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['rut'], name='trabajador_rut_idx'),
        ),
    ]
