# Generated by Django 4.2.26 on 2025-12-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0002_alter_agendamiento_options_alter_incidencia_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agendamiento',
            name='agend_trab_est_idx',
        ),
        migrations.RemoveIndex(
            model_name='agendamiento',
            name='agend_ciclo_est_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='ticket_trabajador_ciclo_idx',
        ),
        migrations.RenameIndex(
            model_name='incidencia',
            new_name='incid_est_fecha_idx',
            old_name='incid_estado_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='incidencia',
            new_name='incid_tipo_est_idx',
            old_name='incid_tipo_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='ticket_est_fecha_idx',
            old_name='ticket_estado_fecha_idx',
        ),
        migrations.AddIndex(
            model_name='agendamiento',
            index=models.Index(fields=['trabajador', 'estado', 'ciclo'], name='agend_trab_est_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamiento',
            index=models.Index(fields=['estado', 'fecha_retiro'], name='agend_est_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['codigo'], name='incid_codigo_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['trabajador', 'estado'], name='incid_trab_est_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['trabajador', 'ciclo', 'estado'], name='ticket_trab_ciclo_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='ticket_created_idx'),
        ),
    ]
