# Generated by Django 4.2.26 on 2025-12-01 00:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0003_remove_agendamiento_agend_trab_est_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('tipo_caja', models.CharField(choices=[('Estándar', 'Estándar'), ('Premium', 'Premium')], max_length=20)),
                ('accion', models.CharField(choices=[('agregar', 'Agregado'), ('retirar', 'Retirado')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('usuario', models.CharField(blank=True, max_length=80)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='totem.sucursal')),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
                'indexes': [models.Index(fields=['fecha'], name='stockmov_fecha_idx'), models.Index(fields=['tipo_caja'], name='stockmov_tipo_idx'), models.Index(fields=['accion'], name='stockmov_accion_idx')],
            },
        ),
    ]
