# Generated by Django 4.2.26 on 2025-12-01 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0004_stockmovimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(blank=True, max_length=255)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('creados', models.PositiveIntegerField(default=0)),
                ('actualizados', models.PositiveIntegerField(default=0)),
                ('sin_beneficio', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomina_cargas', to='totem.ciclo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomina_cargas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_carga', '-id'],
                'indexes': [models.Index(fields=['fecha_carga'], name='totem_nomin_fecha_c_7f353f_idx'), models.Index(fields=['ciclo'], name='totem_nomin_ciclo_i_42baab_idx')],
            },
        ),
    ]
