# Generated by Django 4.2.26 on 2025-12-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0005_nominacarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovimiento',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockmovimiento',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
