# Generated by Django 4.2.26 on 2025-12-04 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0007_usuario_debe_cambiar_contraseña'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tipo de Beneficio',
                'verbose_name_plural': 'Tipos de Beneficios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='ciclo',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Ciclo', 'verbose_name_plural': 'Ciclos'},
        ),
        migrations.AddField(
            model_name='ciclo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción o notas del ciclo'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre descriptivo del ciclo (ej: Navidad 2025, Verano 2026)', max_length=200),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='beneficios_activos',
            field=models.ManyToManyField(blank=True, help_text='Beneficios disponibles en este ciclo', related_name='ciclos', to='totem.tipobeneficio'),
        ),
    ]
