# Generated by Django 4.2.26 on 2025-12-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0009_populate_default_tipo_beneficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipobeneficio',
            name='tipos_contrato',
            field=models.JSONField(blank=True, default=list, help_text="Lista de tipos de contrato que reciben este beneficio (ej: ['planta', 'contrata'])"),
        ),
    ]
