# Generated by Django 4.2.26 on 2025-12-04 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0010_tipobeneficio_tipos_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficioTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_verificacion', models.CharField(db_index=True, max_length=100, unique=True)),
                ('qr_data', models.TextField(blank=True, help_text='Datos del QR generado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('retirado', 'Retirado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('bloqueado', models.BooleanField(default=False, help_text='Si está bloqueado, no puede retirar')),
                ('motivo_bloqueo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Beneficio Trabajador',
                'verbose_name_plural': 'Beneficios Trabajadores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidacionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_escaneado', models.CharField(help_text='Código del QR/manual ingresado', max_length=100)),
                ('resultado', models.CharField(choices=[('exitoso', 'Exitoso'), ('rechazado', 'Rechazado'), ('error', 'Error')], max_length=20)),
                ('caja_validada', models.CharField(blank=True, help_text='Número/código de caja física entregada', max_length=100)),
                ('caja_coincide', models.BooleanField(default=False, help_text='¿La caja coincide con la asignada?')),
                ('notas', models.TextField(blank=True)),
                ('fecha_validacion', models.DateTimeField(auto_now_add=True)),
                ('beneficio_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='totem.beneficiotrabajador')),
                ('guardia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones_cajas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validación de Caja',
                'verbose_name_plural': 'Validaciones de Cajas',
                'ordering': ['-fecha_validacion'],
            },
        ),
        migrations.CreateModel(
            name='CajaBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la caja (ej: Premium, Estándar, Básica)', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo_tipo', models.CharField(help_text='Código único para identificar este tipo de caja (ej: CAJ-NAV-PREMIUM)', max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='totem.tipobeneficio')),
            ],
            options={
                'verbose_name': 'Caja de Beneficio',
                'verbose_name_plural': 'Cajas de Beneficios',
                'unique_together': {('beneficio', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='beneficiotrabajador',
            name='caja_beneficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='totem.cajabeneficio'),
        ),
        migrations.AddField(
            model_name='beneficiotrabajador',
            name='ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios_asignados', to='totem.ciclo'),
        ),
        migrations.AddField(
            model_name='beneficiotrabajador',
            name='tipo_beneficio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totem.tipobeneficio'),
        ),
        migrations.AddField(
            model_name='beneficiotrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='totem.trabajador'),
        ),
        migrations.AlterUniqueTogether(
            name='beneficiotrabajador',
            unique_together={('trabajador', 'ciclo', 'tipo_beneficio')},
        ),
    ]
