# Generated by Django 4.2.26 on 2025-12-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0011_beneficiotrabajador_validacioncaja_cajabeneficio_and_more'),
    ]

    operations = [
    ]
