# Generated by Django 4.2.26 on 2025-12-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0012_agregar_modelos_caja_beneficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipobeneficio',
            name='requiere_validacion_guardia',
            field=models.BooleanField(default=False, help_text='Si es True, el guardia debe verificar la entrega de este beneficio con QR. Si es False, es entrega normal sin validación.'),
        ),
    ]
