# Generated by Django 5.2.8 on 2025-12-07 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0013_tipobeneficio_requiere_validacion_guardia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cajabeneficio',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cajabeneficio',
            name='beneficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='totem.tipobeneficio'),
        ),
    ]
