# Generated by Django 4.2.26 on 2025-12-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0014_alter_cajabeneficio_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiotrabajador',
            name='qr_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Payload del QR serializado (JSON: beneficio_id, trabajador_rut, timestamp, tipo_beneficio)'),
        ),
        migrations.AddField(
            model_name='beneficiotrabajador',
            name='qr_signature',
            field=models.CharField(blank=True, help_text='Firma HMAC-SHA256 del payload (hex encoded, 64 caracteres)', max_length=64),
        ),
    ]
