# Generated by Django 4.2.26 on 2025-12-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0015_beneficiotrabajador_qr_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipobeneficio',
            name='es_caja',
            field=models.BooleanField(default=False, help_text='Si es True, este beneficio es una caja física que requiere validación con guardia'),
        ),
    ]
