# Generated by Django 6.0 on 2025-12-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0016_add_es_caja_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='contrato',
            field=models.CharField(blank=True, choices=[('indefinido', 'Indefinido'), ('plazo_fijo', 'Plazo Fijo'), ('part_time', 'Part Time'), ('honorarios', 'Honorarios'), ('externos', 'Externos')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='sucursal',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tipobeneficio',
            name='tipos_contrato',
            field=models.JSONField(blank=True, default=list, help_text="Lista de tipos de contrato que reciben este beneficio (ej: ['indefinido', 'plazo_fijo'])"),
        ),
    ]
