# Generated by Django 4.2.26 on 2025-12-14 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0010_add_seccion_and_stock_fields'),
        ('totem', '0017_trabajador_contrato_trabajador_sucursal_and_more'),
    ]

    operations = [
    ]
